In [193]:
import numpy as np
import pandas as pd 

In [219]:
data = np.array(np.arange(0,16).reshape(4,4)).astype(np.float)
data[1,1],data[3,2] = np.nan,np.nan
data

array([[ 0.,  1.,  2.,  3.],
       [ 4., nan,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., nan, 15.]])

In [199]:
df = pd.DataFrame(data,columns=['zero','one','two','three'])
df

zero   one   two  three
0   0.0   1.0   2.0    3.0
1   4.0   NaN   6.0    7.0
2   8.0   9.0  10.0   11.0
3  12.0  13.0   NaN   15.0

In [224]:
# v1 = df['one'].mean()
# nv1 = round(v1,2)
# v2 = df['two'].mean()
# newdf = df.fillna({'one':nv1,'two':v2})
# newdf


In [311]:

df.columns.name = 'col'
df.index.name = 'id'
s.shape

(17,)

In [518]:
s = pd.Series(data.flatten())
# s.dtype
# s.values
# s.isna()
# s[[2,3]]
s[16] = 10
# s
# s[s > 9]
# np.log(s)
# s.unique()
# s.value_counts()
# s[s.isin([10])]
# s.notnull()

# series 作为字典
# s1 = pd.Series({
#     'name':'rbp',
#     'age':'100'
# })
# s1.index.name = 'strr'

df1 = pd.DataFrame({
    'name':('rbp','xxy'),
    'age':(12,32),
    'weight':['123','75']
})

# df1.age
# df1.ix[1]

In [501]:
# df1.ix[1]
# df1.ix[[0,1]]
# df1[0:1]
# df1[df1.isin([12,'75'])]

# del df1['age']
# df1
# s.index.is_unique
ser = pd.Series([1,6,2,3,8],index=['c','f','w','a','t'])

# ser1 = ser.reindex(range(13),method='ffill')
# ser1


In [429]:
df1.drop('name',axis=1)

weight
0    123
1     75

In [455]:
# print(ser)
# ser.drop([3,13])del 
# # del ser[5]
# ser.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [525]:
# ser
# ser.sort_index(ascending=False)
# # ser.sort_values()
# df1.sort_values(by='weight',ascending=False)

# ser.sort_index()
# print(ser)
# ser.rank()
print(df1)
df1.corr()
df1.cov()

  name  age weight
0  rbp   12    123
1  xxy   32     75


age
age  200.0

In [542]:
ser[['w','t']] = None
# ser.dropna()

ser.fillna({'w':666,'t':'777'})

c      1
f      6
w    666
a      3
t    777
dtype: object

In [628]:
mser = pd.Series(np.random.random(8),index=[['whitle','whitle',
	'whitle','blue','blue','red','red','red'],['up','down',
	'right','up','down','up','down','left']])
# print(mser)
# mser.index.levels

# clone_mser = mser.unstack()
# # clone_mser

# # clone_mser.stack()
# clone_mser
print(mser)
mser.iloc[6]
mser.loc['whitle']['right']


whitle  up       0.439956
        down     0.490531
        right    0.641409
blue    up       0.264126
        down     0.174094
red     up       0.142786
        down     0.257035
        left     0.154860
dtype: float64


0.6414088132341716

In [605]:
mframe = pd.DataFrame(np.random.randn(16).reshape(4,4),index=[
	['whitle','whitle','red','red'],['up','down','up','down']],
	columns=[['pen','pen','paper','paper'],[1,2,1,2]])
mframe

pen               paper          
                    1         2         1         2
whitle up   -0.359752  1.145868  1.375214 -0.774601
       down -0.079908  0.853357 -0.260338  1.134252
red    up   -1.635433 -0.662089 -0.805760  0.079327
       down -0.339098 -0.313601 -0.309173  1.143221

In [650]:
mframe.columns.names = ['object','id']
mframe.index.names = ['color','status']
nmframe = mframe.swaplevel('color','status')


In [634]:
# nmframe.sort_values(by='status')
mframe.iloc[2][2]


-0.8057597112132496

In [646]:
df1 = pd.DataFrame({
 'year': [2016, 2016, 2017, 2017, 2018],
 'fruit': ['apple', 'banana', 'apple', 'banana', 'apple'],
 'production': [10, 30, 20, 70, 100],
 'profits': [40, 30, 60, 80,10],
})
print(df1)
df2 = df1.set_index(['year','fruit'])
df2

   year   fruit  production  profits
0  2016   apple          10       40
1  2016  banana          30       30
2  2017   apple          20       60
3  2017  banana          70       80
4  2018   apple         100       10


production  profits
year fruit                      
2016 apple           10       40
     banana          30       30
2017 apple           20       60
     banana          70       80
2018 apple          100       10

In [2]:
# df2.sum(level=['year','fruit'])
df2.loc[2017,'apple']['profits']
df2.loc[:]['profits']
df2.iloc[:,1]

NameError: name 'df2' is not defined

In [1]:
df2.reindex()

NameError: name 'df2' is not defined

In [3]:
import pandas as pd 
import numpy as np

In [114]:
df = pd.DataFrame({
    'item':['ball','mug','pen','pencil','ashtray'],
    'color':['black','rosso','verde','black','yellow']
})

df

item   color
0     ball   black
1      mug   rosso
2      pen   verde
3   pencil   black
4  ashtray  yellow

In [115]:
# newcolors = {'rosso':'red','verde':'green'}
# df.replace(newcolors,inplace=True)
# df

price = {
    'ball':2.23,
    
    'pen':5.6,
    'pencil':5.4,
    'ashtray':45,
    'mug':52
}

df['price'] = df['item'].map(price)
df

item   color  price
0     ball   black   2.23
1      mug   rosso  52.00
2      pen   verde   5.60
3   pencil   black   5.40
4  ashtray  yellow  45.00

In [118]:
neindex = {
    0:'first',
    1:'two',
    3:'three',
    4:'fourth',
    2:'second'
}

col = {
    'item':'newitem',
    'color':'colors',
    'price':'prices'
}

df.rename(index=neindex,columns=col)

newitem  colors  prices
first      ball   black    2.23
two         mug   rosso   52.00
second      pen   verde    5.60
three    pencil   black    5.40
fourth  ashtray  yellow   45.00

In [209]:
# for name,values in df.groupby(df['color']):
#     print(name)
#     print(values)
def f(series):
    return series.max() - series.min()
print(ndf)

ndf = df['price'].groupby(df['color']).agg([f,'max','mean']).add_prefix('f_')
nmdf = pd.merge(df,ndf,left_on='color',right_index=True)
print(nmdf)
nmdf[['f_mean','price']].groupby(nmdf['color']).transform(np.sum).add_prefix('tot_')

         f_f  f_max  f_mean
color                      
black   3.17    5.4   3.815
rosso   0.00   52.0  52.000
verde   0.00    5.6   5.600
yellow  0.00   45.0  45.000
      item   color  price   f_f  f_max  f_mean
0     ball   black   2.23  3.17    5.4   3.815
3   pencil   black   5.40  3.17    5.4   3.815
1      mug   rosso  52.00  0.00   52.0  52.000
2      pen   verde   5.60  0.00    5.6   5.600
4  ashtray  yellow  45.00  0.00   45.0  45.000


tot_f_mean  tot_price
0        7.63       7.63
3        7.63       7.63
1       52.00      52.00
2        5.60       5.60
4       45.00      45.00

In [207]:
ser = pd.Series([1,3,np.nan,56,9,np.nan,48])
ser.replace(np.nan,0,inplace=True)
ser

0     1.0
1     3.0
2     0.0
3    56.0
4     9.0
5     0.0
6    48.0
dtype: float64

In [64]:
data = np.arange(100)
bins = [0,25,50,75,100]
cat = pd.cut(data,bins=bins,labels=['25以下','25-50','50-75','75-100'])
# cat.codes
# cat.categories
pd.value_counts(cat)

50-75     25
25-50     25
25以下      25
75-100    24
dtype: int64

In [72]:
pd.qcut(data,8)

[(-0.001, 12.375], (-0.001, 12.375], (-0.001, 12.375], (-0.001, 12.375], (-0.001, 12.375], ..., (86.625, 99.0], (86.625, 99.0], (86.625, 99.0], (86.625, 99.0], (86.625, 99.0]]
Length: 100
Categories (8, interval[float64]): [(-0.001, 12.375] < (12.375, 24.75] < (24.75, 37.125] < (37.125, 49.5] < (49.5, 61.875] < (61.875, 74.25] < (74.25, 86.625] < (86.625, 99.0]]

In [93]:
randframe = pd.DataFrame(np.random.randn(1000,5))
randframe.describe()

0            1            2            3            4
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.004686     0.027083     0.028718    -0.023054    -0.031744
std       1.024211     0.984219     1.002372     1.001450     0.967174
min      -3.470974    -3.196591    -2.987798    -3.528122    -2.880723
25%      -0.685345    -0.663332    -0.666122    -0.715534    -0.646735
50%      -0.038960     0.020612     0.019957    -0.017063    -0.042415
75%       0.657664     0.686533     0.694491     0.708868     0.636266
max       3.476544     3.153167     3.181073     3.031963     3.141638

In [95]:
randframe[(np.abs(randframe) > 3*np.std(randframe)).any(1)]
# help(any)

0         1         2         3         4
91  -3.407860  0.236116  0.925266  0.718969 -0.429051
154 -0.121932  3.153167  0.057530  1.073864 -1.457698
214 -3.206913 -0.896459  1.919911 -2.146459  0.903570
386 -0.658305 -0.932061 -0.805276 -3.528122  0.516609
401 -0.041522 -0.106071  3.181073  0.567297 -0.844769
421 -3.470974 -2.101240 -2.276255  0.772449 -0.333565
449  0.387762  1.240622 -0.732313  1.041057  3.141638
457  0.380953  3.069187 -0.175449  0.527539  1.706339
651 -0.266574  0.301291 -0.441412  3.031963  0.469998
671  1.080591 -3.196591 -0.986845 -0.268930 -0.595303
719  3.476544  0.768370 -0.383033 -0.778780  0.590233

In [104]:
nframe = pd.DataFrame(np.random.randn(20).reshape(5,4))
order = np.random.permutation(5)
order

array([2, 0, 3, 1, 4])

In [106]:
nframe.take(order)

0         1         2         3
2  0.229605  1.559798  0.258667 -0.001288
0  0.132491  1.887612  1.923993  2.591980
3  0.706337 -2.062295  0.696999  0.524709
1 -0.537245 -0.074873  1.060319  1.408386
4 -2.762191  0.457433 -1.291683  1.307669

In [113]:
sample = np.random.randint(0,len(nframe),size=3)
print(sample)
nframe.take(sample)

[2 0 1]


0         1         2         3
2  0.229605  1.559798  0.258667 -0.001288
0  0.132491  1.887612  1.923993  2.591980
1 -0.537245 -0.074873  1.060319  1.408386

In [63]:
dframe = pd.DataFrame(np.random.randn(3,3))

dframe

NameError: name 'pd' is not defined

In [64]:
order = {
    0:'num',
    1:'price',
    2:'weigth'
}
dframe.rename(columns=order,inplace=True)
dframe['name'] = ['apple','orange','shi']
print(dframe)
dframe.groupby(by=['price','name'])[['num']].sum()


NameError: name 'dframe' is not defined

In [65]:
url = 'https://hz.house.ifeng.com/news/2014_10_28-50087618_1.shtml'
table = pd.read_html(url,header=1)[0]
df = pd.DataFrame(table)
# df.to_csv('html.csv',encoding='utf-8')
# df
# # table

NameError: name 'pd' is not defined

In [66]:
url = 'https://www.baidu.com'
pd.read_html(url,header=1)

NameError: name 'pd' is not defined

In [67]:
from datetime import datetime
from datetime import timedelta


In [68]:
start = datetime(2018,12,10)
start + timedelta(7)*2 

datetime.datetime(2018, 12, 24, 0, 0)

In [69]:
date = datetime(2018,2,3)
# td = str(date)
# dt = datetime(td)
# type(dt)
date.strftime("%m-%Y-%d")

'02-2018-03'

In [70]:
v = "2011-5-9"
d = datetime.strptime(v,'%Y-%m-%d')
type(d)

datetime.datetime

In [71]:
dates = ["7/4/2012","4/6/4590"]
[datetime.strptime(date,"%m/%d/%Y") for date in dates]

[datetime.datetime(2012, 7, 4, 0, 0), datetime.datetime(4590, 4, 6, 0, 0)]

In [72]:
from dateutil.parser import parse
parse(v)
parse('4/6/6789',dayfirst=True)

datetime.datetime(6789, 6, 4, 0, 0)

In [10]:
import numpy as np
import pandas as pd 
ts = pd.Series(np.random.randn(1000),
               index=pd.date_range(1/2/2000,periods=1000))
ts['1/1/1971':'2/3/1971']

1971-01-01    0.439162
1971-01-02   -0.304190
1971-01-03    1.697197
1971-01-04    0.277763
1971-01-05    0.757111
1971-01-06    0.354298
1971-01-07   -0.934556
1971-01-08   -1.096478
1971-01-09   -0.208089
1971-01-10   -0.813260
1971-01-11   -1.133568
1971-01-12    0.038239
1971-01-13    0.683620
1971-01-14    0.408126
1971-01-15   -0.894289
1971-01-16    0.086392
1971-01-17   -0.114059
1971-01-18    0.343333
1971-01-19   -1.075677
1971-01-20   -0.268804
1971-01-21    0.151682
1971-01-22    0.392904
1971-01-23    0.627687
1971-01-24    0.105060
1971-01-25   -0.968143
1971-01-26   -1.160899
1971-01-27   -1.004152
1971-01-28    1.798644
1971-01-29   -0.005450
1971-01-30    0.169878
1971-01-31   -1.223493
1971-02-01   -0.313224
1971-02-02    0.085641
1971-02-03    0.938338
Freq: D, dtype: float64

In [12]:
ts.truncate(after='1/3/1970')

1970-01-01   -0.867962
1970-01-02    1.187844
1970-01-03   -1.611072
Freq: D, dtype: float64

In [26]:
dateindex = pd.DatetimeIndex(['1/1/2000','1/2/2000','1/2/2000','1/3/2000'])
                              
ts1 = pd.Series(np.random.randn(4),index=dateindex)
ts1.index.is_unique
# [np.sum(v) for name,v in ts1.groupby(by=ts1.index)]
  
ts1.groupby(by=ts1.index).sum()
ts1.groupby(by=ts1.index).count()

2000-01-01    1
2000-01-02    2
2000-01-03    1
dtype: int64

In [41]:
# pd.date_range('1/1/2000','1/1/2001')
st = pd.Series(np.random.randn(4),index=pd.date_range('1/1/2000',periods=4))
print(st)
st.shift(2,freq='D')

2000-01-01   -1.806042
2000-01-02    0.373510
2000-01-03    0.875829
2000-01-04   -0.221603
Freq: D, dtype: float64


2000-01-03   -1.806042
2000-01-04    0.373510
2000-01-05    0.875829
2000-01-06   -0.221603
Freq: D, dtype: float64

In [68]:
t = pd.DataFrame(np.random.uniform(10,50,(100,1)),index=pd.date_range('2000-1-1',periods=100))
t.resample('10D').ffill()

0
2000-01-01  28.317402
2000-01-11  44.635072
2000-01-21  14.433605
2000-01-31  14.126860
2000-02-10  11.656114
2000-02-20  15.036239
2000-03-01  17.406240
2000-03-11  30.145007
2000-03-21  24.265393
2000-03-31  25.659099